stages:
  - deploy

deploy:
  stage: deploy
  image: debian:jessie
  only:
    - "master"
  before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  ##
  ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
  ## following two lines.
  ##
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh fluentlydata@${DEPLOYMENT_SERVER_IP} "mkdir -p /home/${CI_PROJECT_PATH}"
    - scp -r * fluentlydata@${DEPLOYMENT_SERVER_IP}:/home/${CI_PROJECT_PATH}/
    - ssh fluentlydata@${DEPLOYMENT_SERVER_IP} "cd /home/${CI_PROJECT_PATH}; docker-compose -f docker-compose.prod.yml up --build -d"


