version: '3'

services:

  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    ports:
      - "8000:8000"
    command: flask run --host=0.0.0.0 --port 8000 
    environment:
      FLASK_APP: /usr/src/app.py
      FLASK_DEBUG: 1
    volumes:
      - ./dash_app/:/usr/src


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash_app
