version: '3'

services:

  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    environment:
      VIRTUAL_HOST: dash.fluentlydata.ch
    command: gunicorn -w 1 --bind 0.0.0.0:80 app:server

networks:                                                                                           
  default:                                                                                          
    external:                                                                                       
      name: nginx-net

